Repository rjsf-team/react-jsonschema-form, pull requests merged in 2019-03, with the labels that each got.

#1130 Add more schemas to validate against
  docs/validation.md
  package-lock.json
  package.json
  src/components/Form.js
  src/components/fields/SchemaField.js
  src/validate.js
  test/ArrayField_test.js
  test/Form_test.js
  test/validate_test.js
Labels: awaiting review

#1158 Bug Fix empty html useless added by PR #1123 / v1.2.0
  .gitignore
  src/components/fields/SchemaField.js
  test/ArrayFieldTemplate_test.js
  test/ArrayField_test.js
  test/ObjectField_test.js
  test/SchemaField_test.js
Labels: awaiting changes

#1194 Limit cases where "required" attribute is used on checkboxes
  src/components/widgets/CheckboxWidget.js
  test/BooleanField_test.js
Labels: awaiting review

#1215 fix: playground dependencies demos with plain text
  playground/samples/propertyDependencies.js
  playground/samples/schemaDependencies.js
Labels: awaiting review

#1213 Basic support for 'nullable' types
  docs/index.md
  playground/samples/index.js
  playground/samples/nullable.js
  src/utils.js
  test/utils_test.js
Labels: awaiting changes

#1218 #804 - Bug Fix - Empty divs are created
  src/components/fields/ArrayField.js
  src/components/fields/DescriptionField.js
  src/components/fields/SchemaField.js
  test/ArrayFieldTemplate_test.js
  test/SchemaField_test.js
Labels: awaiting review

#946 schema is not an html attribute
  docs/form-customization.md
Labels: awaiting review

#814 Removed throwing error when there's an extraneous property in ui:order
  src/utils.js
  test/ObjectField_test.js
  test/utils_test.js
Labels: awaiting review

#1234 Fix #1233 : Exclude File object from isObject detection
  src/utils.js
  test/setup-jsdom.js
  test/utils_test.js
Labels: awaiting changes

#1223 Document placeholder and autofocus widget props
  docs/advanced-customization.md
Labels: awaiting review, documentation
