Repository rjsf-team/react-jsonschema-form, pull requests merged in 2019-02, with the labels that each got.

#1174 Infer field type from const value
  src/utils.js
  test/const_test.js
  test/utils_test.js
Labels: awaiting review

#1171 Add various always-ignore files and directories to .gitignore
  .gitignore
Labels: awaiting review

#1172 Return original submit event as second param
  docs/index.md
  playground/app.js
  src/components/Form.js
  test/Form_test.js
Labels: awaiting response

#1163 Feature/fix enum empty bug
  test/NumberField_test.js
  test/StringField_test.js
  test/enum_test.js
Labels: awaiting review

#1183 Improve handling of decimal points and trailing zeroes in numbers
  src/components/fields/NumberField.js
  src/components/widgets/BaseInput.js
  test/ArrayField_test.js
  test/Form_test.js
  test/NumberField_test.js
  test/uiSchema_test.js
Labels: awaiting changes
