Repository rjsf-team/react-jsonschema-form, pull requests merged in 2019-08, with the labels that each got.

#1413 Fix publicPath for netlify deploy previews
  webpack.config.prod.js
Labels: playground

#1401 Key changes on additionalProperties items no longer suffer data loss.
  src/components/fields/ObjectField.js
  src/components/fields/SchemaField.js
  test/ObjectField_test.js
Labels: needs tests

#1406 Fix omitData for top level array
  src/components/Form.js
  test/Form_test.js
Labels: needs tests

#1402 Adding support for $ref pointers to additionalProperties.
  src/components/fields/ObjectField.js
  src/utils.js
  test/Form_test.js
  test/utils_test.js
Labels: additionalProperties
