Repository rjsf-team/react-jsonschema-form, pull requests merged in 2019-06, with the labels that each got.

#1227 #1209 | allow widget to be wrapped as React.ForwardedRef
  package-lock.json
  package.json
  src/utils.js
  test/utils_test.js
Labels: awaiting review

#1292 Default type to `object` if undefined
  src/utils.js
  test/utils_test.js
Labels: awaiting response

#1264 Ensure defaults are passed along for multiselect arrays when minItems…
  src/utils.js
  test/utils_test.js
Labels: awaiting changes

#1302 Allowing AnyOfField or OneOfField to use schema
  src/components/fields/SchemaField.js
Labels: awaiting changes, awaiting response
