Repository rjsf-team/react-jsonschema-form, pull requests merged in 2021-03, with the labels that each got.

#2156 Pass oneOf / anyOf subschemas to altSchema optionsList
  docs/advanced-customization/custom-widgets-fields.md
  package-lock.json
  package.json
  packages/core/index.d.ts
  packages/core/src/utils.js
  packages/core/test/utils_test.js
Labels: awaiting changes

#2263 fixed link to ajv issue on incorrect schemaPath
  docs/usage/validation.md
  packages/core/test/validate_test.js
Labels: awaiting changes

#2031 Drop support for node 8 / 9
  .github/workflows/ci.yml
  packages/antd/package.json
  packages/bootstrap-4/package.json
  packages/core/package.json
  packages/fluent-ui/package.json
  packages/playground/package.json
  packages/semantic-ui/package.json
Labels: breaking change

#2299 Drop support for node 10, improve build process
  .github/workflows/ci.yml
  packages/antd/package.json
  packages/bootstrap-4/package.json
  packages/core/package.json
  packages/fluent-ui/package.json
  packages/playground/package.json
  packages/semantic-ui/package.json
Labels: breaking change

#2290 Build files on GitHub Actions before deploying to deploy previews on Netlify
  .github/workflows/ci.yml
  PULL_REQUEST_TEMPLATE.md
Labels: devops

#2289 Split chunks for playground bundle
  packages/playground/webpack.config.dev.js
  packages/playground/webpack.config.dist.js
  packages/playground/webpack.config.prod.js
Labels: devops

#2211 No core-js in core
  babel.config.js
  docs/3.x upgrade guide.md
  mkdocs.yml
  packages/antd/babel.config.js
  packages/antd/package-lock.json
  packages/antd/package.json
  packages/bootstrap-4/package.json
  packages/core/babel.config.js
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/components/fields/ArrayField.js
  packages/core/src/utils.js
  packages/core/webpack.config.dist.js
  packages/fluent-ui/package.json
  packages/material-ui/package.json
  packages/playground/.babelrc
  packages/playground/package-lock.json
  packages/playground/package.json
  packages/semantic-ui/babel.config.js
  packages/semantic-ui/package-lock.json
  packages/semantic-ui/package.json
Labels: breaking change

#2306 fix: readonly checkbox for bootstrap-4
  packages/bootstrap-4/src/CheckboxWidget/CheckboxWidget.tsx
  packages/bootstrap-4/src/CheckboxesWidget/CheckboxesWidget.tsx
  packages/bootstrap-4/test/__snapshots__/CheckboxWidget.test.tsx.snap
  packages/bootstrap-4/test/__snapshots__/CheckboxesWidget.test.tsx.snap
  packages/bootstrap-4/test/__snapshots__/Form.test.tsx.snap
Labels: bootstrap-4
